{% set name = "mkdocs-material-extensions" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc1afaf721306e32c272878488b3ec4babd073f4ba7f0a740608bdd31057743b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - mkdocs-material >=5.0.0
    - python >=3.5

test:
  imports:
    - materialx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mkdocs-material-extensions/
  summary: Extension pack for Python Markdown
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - marcelotrevisani
